### ISSUE TITLE
bootstrap/app.php

### ISSUE THREAD

**Issue by sbreiler** [GlaivePro/Hidevara#2]
Hi, i edited the file "bootstrap/app.php" as descriped in usage

```php
// bootstrap/app.php

// This (or something similar with another namespace instead of App) is already there
// $app->singleton(
//     Illuminate\Contracts\Debug\ExceptionHandler::class,
//     App\Exceptions\Handler::class
// );

// Add this after (preferrably exactly after) the above lines.
$app->extend(
	Illuminate\Contracts\Debug\ExceptionHandler::class,
	function($handler) {
		return new GlaivePro\Hidevara\HidingHandler($handler);
});
```

I get following error in my apache log:
```
[Wed Apr 17 14:51:22.493397 2019] [php7:error] [pid 2728] [client 192.168.178.XXX:58848] PHP Fatal error:  
	Uncaught Illuminate\\Contracts\\Container\\BindingResolutionException: 
	Target [Illuminate\\Contracts\\Debug\\ExceptionHandler] is not instantiable. 
	in /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Container/Container.php:962
Stack trace:
#0 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): Illuminate\\Container\\Container->notInstantiable('Illuminate\\\\Cont...')
#1 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\\Container\\Container->build('Illuminate\\\\Cont...')
#2 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\\Container\\Container->resolve('Illuminate\\\\Cont...', Array)
#3 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\\Container\\Container->make('Illuminate\\\\Cont...', Array)
#4 /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(159): Illuminate\\Foundation\\A in /var/www/html/XXX/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 962, referer: XXX
```

using laravel/framework version v5.8.4

Any ideas why this happens? Thanks!

**Comment by tontonsb** [comment]
Hey,

Could it be that you commented out the original binding as well?

I mean this part: 
```php
$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);
```
The point of it in the usage was - this is already there, just leave it as it is and insert the code AFTER that piece.

**Comment by sbreiler** [comment]
Hi,

you're spot on! I commented the part with _Illuminate\Contracts\Debug\ExceptionHandler_ out.

Maybe we could improve the README just a little bit 😅

<hr />

To deal with the cases where the app crashes before loading providers, you should open your `bootstrap/app.php` and add this part:
```php
$app->extend(
	Illuminate\Contracts\Debug\ExceptionHandler::class,
	function($handler) {
		return new GlaivePro\Hidevara\HidingHandler($handler);
});
```

Put this right after the binding of the exception handler:
```php
// inside bootstrap/app.php

// This (or something similar with another namespace instead of App) is already there
  $app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
  );
  
// *put above code here*
```

**Comment by tontonsb** [comment]
Thanks for the suggestion, I reworded it a bit and split into pieces as you suggested!
